### PR TITLE
Fix filename(case-sensitive) of QNHttpDelegate.h importing.

### PR DESCRIPTION
**Pull request by sutra**
This could cause failure when depending on this SDK by CocoaPods.

### CODE REVIEW

**Comment by sutra** [comment]
Build failure due to:
```
The platform of the target `QiniuSDK iOS` (iOS 6.0) is not compatible with `AFNetworking (2.6.0)` which has a minimum requirement of iOS 7.0 - OS X 10.9 - watchos 2.0.
```

**Comment by longbai** [comment]
LGTM, @sutra 多谢了，我来改下依赖的问题

**Comment by longbai** [comment]
依赖，避不过去的痛 :(

**Comment by longbai** [comment]
version fixed #63

**Pull request merged**
